### ISSUE TITLE
`mutual_info` metric on continuous `gene_data`

### ISSUE THREAD

**Issue by MaybeJustJames** [GiadaLalli/ISN-tractor#26]
When continuous data is passed in for `gene_data` (rather than `{0, 1, 2}` for SNPs) we get the following warning:

```
Clustering metrics expects discrete values but received continuous values for label, and continuous values for target
```

**Comment by GiadaLalli** [comment]
Maybe a way to solve it is to discretize the data before passing it to the metric:

bins = np.linspace(np.min(gene_data), np.max(gene_data), 10)
gene_data_binned = np.digitize(gene_data, bins)

and then give to mutual_info the discretized data

**Comment by MaybeJustJames** [comment]
Solution: Remove the `mutual_info` as a supplied metric.
